// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Lovable Cloud Supabase credentials
const SUPABASE_URL = "https://cteiidzqhrernptuubzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZWlpZHpxaHJlcm5wdHV1Ynp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMTQ1NDksImV4cCI6MjA3OTc5MDU0OX0.vvHVeKBaJTcDVwlEclFKd08vSi_eoJ8zvOMaAl8UiBU";

// Import with:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        "x-client-info": "admin-panel",
      },
    },
  }
);
