// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Updated with your actual Supabase credentials
const SUPABASE_URL = "https://mcglwbcsyvtbmuegfamt.supabase.co";

const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZ2x3YmNzeXZ0Ym11ZWdmYW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNTk1OTksImV4cCI6MjA3OTkzNTU5OX0.7r43O3zJOpucG4GfDG3X-z_BKLxd0my8BFSOrre-KDo";

// Import with:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        "x-client-info": "admin-panel",
      },
    },
  }
);
